#!/bin/bash

##############################################################################
# FrontDash Full Deployment Script
# One command to deploy everything: RDS + EC2 + API
##############################################################################

set -e

cd "$(dirname "$0")"

echo "================================================"
echo "FrontDash Full Deployment"
echo "================================================"
echo ""

# --------------------------------------------------
# Pre-flight checks: Ensure AWS CLI is installed and configured
# --------------------------------------------------
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Please install it first:"
    echo "   https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html"
    exit 1
fi

if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run: aws configure"
    exit 1
fi

echo "✓ AWS CLI configured"
echo ""

# --------------------------------------------------
# STEP 1: Database Setup (RDS PostgreSQL)
#
# Creates the RDS database and outputs:
#   - db-config.txt: Connection details (host, port, user, password)
#   - schema.sql: Table definitions to be applied later
# --------------------------------------------------
if [ -f "db-config.txt" ]; then
    # db-config.txt exists = database was already created before
    echo "Database already exists (found db-config.txt)"
    read -p "Skip database setup? (Y/n): " skip_db
    skip_db=${skip_db:-Y}
    if [[ $skip_db =~ ^[Nn] ]]; then
        ./setup-database.sh
    else
        echo "Skipping database setup"
    fi
else
    echo "Step 1/3: Setting up RDS PostgreSQL database..."
    ./setup-database.sh
fi

echo ""

# --------------------------------------------------
# STEP 2: EC2 Instance Setup
#
# Creates an EC2 instance and outputs:
#   - ec2-config.txt: Instance ID, public IP, security group
#   - deploy-api.sh: Script to upload code and start the server
#   - frontdash-key.pem: SSH key to access the server
#
# Reads db-config.txt to allow EC2 → RDS network access
# --------------------------------------------------
if [ -f "ec2-config.txt" ]; then
    # ec2-config.txt exists = EC2 was already created before
    source ec2-config.txt
    echo "EC2 already exists (found ec2-config.txt)"
    echo "  Instance ID: $INSTANCE_ID"
    echo "  Public IP: $PUBLIC_IP"
    read -p "Skip EC2 setup and just redeploy API? (Y/n): " skip_ec2
    skip_ec2=${skip_ec2:-Y}
    if [[ $skip_ec2 =~ ^[Nn] ]]; then
        ./setup-ec2.sh
    else
        echo "Skipping EC2 setup"
    fi
else
    echo "Step 2/3: Setting up EC2 instance..."
    ./setup-ec2.sh

    # EC2 needs time to boot and run its initialization script
    echo ""
    echo "Waiting 60 seconds for EC2 to fully initialize..."
    sleep 60
fi

echo ""

# --------------------------------------------------
# STEP 3: Deploy API to EC2
#
# Uses deploy-api.sh (generated by setup-ec2.sh) to:
#   1. Copy backend/api/ code to EC2 via SCP
#   2. Copy db-config.txt so the API knows how to connect to RDS
#   3. Run schema.sql to create database tables
#   4. npm install + npm run build (TypeScript → JavaScript)
#   5. Start the API with PM2 (process manager)
# --------------------------------------------------
echo "Step 3/3: Deploying API to EC2..."

if [ ! -f "deploy-api.sh" ]; then
    echo "❌ deploy-api.sh not found. This is generated by setup-ec2.sh"
    exit 1
fi

./deploy-api.sh

# --------------------------------------------------
# Done! Show the user what to do next
# --------------------------------------------------
source ec2-config.txt

echo ""
echo "================================================"
echo "🚀 Deployment Complete!"
echo "================================================"
echo ""
echo "API URL: http://${PUBLIC_IP}:3000"
echo ""
echo "Test it:"
echo "  curl http://${PUBLIC_IP}:3000/health"
echo ""
echo "Update your .env.local:"
echo "  NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}:3000"
echo ""
echo "SSH into server:"
echo "  ssh -i ${KEY_NAME}.pem ubuntu@${PUBLIC_IP}"
echo "================================================"
