#!/bin/bash

##############################################################################
# FrontDash Full Deployment Script
# One command to deploy everything: RDS + EC2 + API
##############################################################################

set -e

cd "$(dirname "$0")"

echo "================================================"
echo "FrontDash Full Deployment"
echo "================================================"
echo ""

# --------------------------------------------------
# Pre-flight checks: Ensure AWS CLI is installed and configured
# --------------------------------------------------
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Please install it first:"
    echo "   https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html"
    exit 1
fi

if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run: aws configure"
    exit 1
fi

echo "✓ AWS CLI configured"
echo ""

# --------------------------------------------------
# STEP 1: S3 Setup (Image Storage)
#
# Creates S3 bucket and IAM role for image uploads:
#   - s3-config.txt: Bucket name, region, IAM role
#   - IAM instance profile for EC2 to access S3
# --------------------------------------------------
if [ -f "s3-config.txt" ]; then
    echo "S3 already configured (found s3-config.txt)"
    read -p "Skip S3 setup? (Y/n): " skip_s3
    skip_s3=${skip_s3:-Y}
    if [[ $skip_s3 =~ ^[Nn] ]]; then
        ./setup-s3.sh
    else
        echo "Skipping S3 setup"
    fi
else
    echo "Step 1/4: Setting up S3 bucket for images..."
    ./setup-s3.sh
fi

echo ""

# --------------------------------------------------
# STEP 2: Database Setup (RDS PostgreSQL)
#
# Creates the RDS database and outputs:
#   - db-config.txt: Connection details (host, port, user, password)
#   - schema.sql: Table definitions to be applied later
# --------------------------------------------------
if [ -f "db-config.txt" ]; then
    # db-config.txt exists = database was already created before
    echo "Database already exists (found db-config.txt)"
    read -p "Skip database setup? (Y/n): " skip_db
    skip_db=${skip_db:-Y}
    if [[ $skip_db =~ ^[Nn] ]]; then
        ./setup-database.sh
    else
        echo "Skipping database setup"
    fi
else
    echo "Step 2/4: Setting up RDS PostgreSQL database..."
    ./setup-database.sh
fi

echo ""

# --------------------------------------------------
# STEP 3: EC2 Instance Setup
#
# Creates an EC2 instance and outputs:
#   - ec2-config.txt: Instance ID, public IP, security group
#   - elastic-ip.txt: Static IP that persists across deployments
#   - deploy-api.sh: Script to upload code and start the server
#   - frontdash-key.pem: SSH key to access the server
#
# Reads db-config.txt to allow EC2 → RDS network access
# Reads s3-config.txt to attach IAM profile for S3 access
# --------------------------------------------------
if [ -f "ec2-config.txt" ]; then
    # ec2-config.txt exists = EC2 was already created before
    source ec2-config.txt
    echo "EC2 already exists (found ec2-config.txt)"
    echo "  Instance ID: $INSTANCE_ID"
    echo "  Public IP: $PUBLIC_IP"
    read -p "Skip EC2 setup and just redeploy API? (Y/n): " skip_ec2
    skip_ec2=${skip_ec2:-Y}
    if [[ $skip_ec2 =~ ^[Nn] ]]; then
        ./setup-ec2.sh
    else
        echo "Skipping EC2 setup"
    fi
else
    echo "Step 3/4: Setting up EC2 instance with Elastic IP..."
    ./setup-ec2.sh
fi

# Load EC2 config for polling
source ec2-config.txt

# Wait for EC2 initialization by polling for the setup-complete flag
echo ""
echo "Waiting for EC2 initialization to complete..."
echo "  (user-data.sh installs Node.js, PostgreSQL client, git)"

MAX_WAIT=300  # 5 minutes max
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
    # Check if setup-complete file exists
    if ssh -i ${KEY_NAME}.pem -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
        ubuntu@${PUBLIC_IP} "test -f /home/ubuntu/setup-complete" 2>/dev/null; then
        echo "  ✓ EC2 initialization complete! (${WAITED} seconds)"
        break
    fi

    echo "  Waiting... (${WAITED} seconds elapsed)"
    sleep 15
    WAITED=$((WAITED + 15))
done

if [ $WAITED -ge $MAX_WAIT ]; then
    echo "  ⚠️  Timeout after ${MAX_WAIT} seconds. Proceeding anyway..."
fi

echo ""

# --------------------------------------------------
# STEP 4: Deploy API to EC2
#
# Uses deploy-api.sh (generated by setup-ec2.sh) to:
#   1. Copy backend/api/ code to EC2 via SCP
#   2. Copy db-config.txt so the API knows how to connect to RDS
#   3. Copy s3-config.txt for image upload configuration
#   4. Run schema.sql to create database tables
#   5. npm install + npm run build (TypeScript → JavaScript)
#   6. Start the API with PM2 (process manager)
# --------------------------------------------------
echo "Step 4/4: Deploying API to EC2..."

if [ ! -f "deploy-api.sh" ]; then
    echo "❌ deploy-api.sh not found. This is generated by setup-ec2.sh"
    exit 1
fi

./deploy-api.sh

# --------------------------------------------------
# STEP 5 (Optional): Deploy Frontend to EC2
#
# Optionally deploy the Next.js frontend to the same EC2:
#   - Clones the repo from GitHub
#   - Builds the Next.js app
#   - Runs on port 3001 via PM2
# --------------------------------------------------
source ec2-config.txt

echo ""
read -p "Deploy frontend to EC2 as well? (y/N): " deploy_frontend
deploy_frontend=${deploy_frontend:-N}

if [[ $deploy_frontend =~ ^[Yy] ]]; then
    echo ""
    echo "Step 5/5: Deploying frontend to EC2..."
    ./setup-frontend.sh
fi

# --------------------------------------------------
# Done! Show the user what to do next
# --------------------------------------------------
echo ""
echo "================================================"
echo "🚀 Deployment Complete!"
echo "================================================"
echo ""
echo "Backend API: http://${PUBLIC_IP}:3000"

if [[ $deploy_frontend =~ ^[Yy] ]]; then
    echo "Frontend:    http://${PUBLIC_IP}:3001"
fi

echo ""
echo "Test backend:"
echo "  curl http://${PUBLIC_IP}:3000/health"
echo ""

if [[ ! $deploy_frontend =~ ^[Yy] ]]; then
    echo "To deploy frontend later:"
    echo "  ./setup-frontend.sh"
    echo ""
    echo "Or update your local .env.local:"
    echo "  NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}:3000"
    echo ""
fi

echo "SSH into server:"
echo "  ssh -i ${KEY_NAME}.pem ubuntu@${PUBLIC_IP}"
echo "================================================"
