#!/bin/bash

##############################################################################
# FrontDash Frontend Deployment Script
# Deploys the Next.js frontend to the EC2 instance
##############################################################################

set -e

cd "$(dirname "$0")"

echo "================================================"
echo "FrontDash Frontend Deployment"
echo "================================================"
echo ""

# --------------------------------------------------
# Load EC2 configuration
# --------------------------------------------------
if [ ! -f "ec2-config.txt" ]; then
    echo "❌ ec2-config.txt not found. Run deploy-all.sh first."
    exit 1
fi

source ec2-config.txt

echo "Deploying frontend to EC2: ${PUBLIC_IP}"
echo ""

# --------------------------------------------------
# Open port 3001 in security group (if not already open)
# --------------------------------------------------
echo "Opening port 3001 in security group..."
aws ec2 authorize-security-group-ingress \
    --group-id $EC2_SG_ID \
    --protocol tcp \
    --port 3001 \
    --cidr 0.0.0.0/0 \
    --region us-east-1 2>/dev/null || echo "  (Port 3001 already open)"
echo ""

# --------------------------------------------------
# Step 1: Clone repo and install dependencies on EC2
# --------------------------------------------------
echo "Step 1: Cloning repository and installing dependencies..."

ssh -i ${KEY_NAME}.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${PUBLIC_IP} << 'ENDSSH'
set -e

# Remove old frontend if exists
if [ -d "/home/ubuntu/frontdash-frontend" ]; then
    echo "  Removing old frontend installation..."
    rm -rf /home/ubuntu/frontdash-frontend
fi

# Clone the repository
echo "  Cloning repository..."
git clone --depth 1 --branch main https://github.com/kassi-bertrand/frontdash.git /home/ubuntu/frontdash-frontend

cd /home/ubuntu/frontdash-frontend

# Install dependencies
echo "  Installing dependencies..."
npm install

echo "✓ Repository cloned and dependencies installed"
ENDSSH

echo "✓ Step 1 complete"
echo ""

# --------------------------------------------------
# Step 2: Create .env file with API URL
# --------------------------------------------------
echo "Step 2: Creating .env file..."

ssh -i ${KEY_NAME}.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${PUBLIC_IP} << ENDSSH
cat > /home/ubuntu/frontdash-frontend/.env << EOF
# FrontDash Frontend Environment Configuration
# Auto-generated by setup-frontend.sh

NEXT_PUBLIC_API_URL=http://${PUBLIC_IP}:3000
EOF

echo "✓ .env file created"
ENDSSH

echo "✓ Step 2 complete"
echo ""

# --------------------------------------------------
# Step 3: Build the Next.js application
# --------------------------------------------------
echo "Step 3: Building Next.js application..."
echo "  (This may take a few minutes...)"

ssh -i ${KEY_NAME}.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${PUBLIC_IP} << 'ENDSSH'
cd /home/ubuntu/frontdash-frontend
npm run build
echo "✓ Build complete"
ENDSSH

echo "✓ Step 3 complete"
echo ""

# --------------------------------------------------
# Step 4: Start the frontend with PM2
# --------------------------------------------------
echo "Step 4: Starting frontend with PM2..."

ssh -i ${KEY_NAME}.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${PUBLIC_IP} << 'ENDSSH'
cd /home/ubuntu/frontdash-frontend

# Stop existing frontend if running
pm2 delete frontdash-frontend 2>/dev/null || true

# Start the frontend on port 3001
PORT=3001 pm2 start npm --name "frontdash-frontend" -- start

# Save PM2 configuration
pm2 save

echo "✓ Frontend started on port 3001"
ENDSSH

echo "✓ Step 4 complete"
echo ""

# --------------------------------------------------
# Done!
# --------------------------------------------------
echo "================================================"
echo "🎉 Frontend Deployment Complete!"
echo "================================================"
echo ""
echo "Frontend URL: http://${PUBLIC_IP}:3001"
echo "Backend API:  http://${PUBLIC_IP}:3000"
echo ""
echo "View logs:"
echo "  ssh -i ${KEY_NAME}.pem ubuntu@${PUBLIC_IP} 'pm2 logs frontdash-frontend'"
echo ""
echo "PM2 status:"
echo "  ssh -i ${KEY_NAME}.pem ubuntu@${PUBLIC_IP} 'pm2 list'"
echo "================================================"
